name: CI
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  release:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: build
        run: |
          python -m pip install setuptools twine wheel
          python setup.py sdist bdist_wheel
      - name: publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
        run: twine upload dist/*
